// Generated by gencpp from file mobile_manipulator_body/velocityRequest.msg
// DO NOT EDIT!


#ifndef MOBILE_MANIPULATOR_BODY_MESSAGE_VELOCITYREQUEST_H
#define MOBILE_MANIPULATOR_BODY_MESSAGE_VELOCITYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mobile_manipulator_body
{
template <class ContainerAllocator>
struct velocityRequest_
{
  typedef velocityRequest_<ContainerAllocator> Type;

  velocityRequest_()
    : sec_int(0)  {
    }
  velocityRequest_(const ContainerAllocator& _alloc)
    : sec_int(0)  {
  (void)_alloc;
    }



   typedef int32_t _sec_int_type;
  _sec_int_type sec_int;





  typedef boost::shared_ptr< ::mobile_manipulator_body::velocityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobile_manipulator_body::velocityRequest_<ContainerAllocator> const> ConstPtr;

}; // struct velocityRequest_

typedef ::mobile_manipulator_body::velocityRequest_<std::allocator<void> > velocityRequest;

typedef boost::shared_ptr< ::mobile_manipulator_body::velocityRequest > velocityRequestPtr;
typedef boost::shared_ptr< ::mobile_manipulator_body::velocityRequest const> velocityRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobile_manipulator_body::velocityRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobile_manipulator_body::velocityRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobile_manipulator_body::velocityRequest_<ContainerAllocator1> & lhs, const ::mobile_manipulator_body::velocityRequest_<ContainerAllocator2> & rhs)
{
  return lhs.sec_int == rhs.sec_int;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobile_manipulator_body::velocityRequest_<ContainerAllocator1> & lhs, const ::mobile_manipulator_body::velocityRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobile_manipulator_body

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mobile_manipulator_body::velocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_manipulator_body::velocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobile_manipulator_body::velocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobile_manipulator_body::velocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_manipulator_body::velocityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_manipulator_body::velocityRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobile_manipulator_body::velocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "635e9bf46a8b2b500c4b25026d911da1";
  }

  static const char* value(const ::mobile_manipulator_body::velocityRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x635e9bf46a8b2b50ULL;
  static const uint64_t static_value2 = 0x0c4b25026d911da1ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobile_manipulator_body::velocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobile_manipulator_body/velocityRequest";
  }

  static const char* value(const ::mobile_manipulator_body::velocityRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobile_manipulator_body::velocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 sec_int\n"
;
  }

  static const char* value(const ::mobile_manipulator_body::velocityRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobile_manipulator_body::velocityRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sec_int);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct velocityRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobile_manipulator_body::velocityRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobile_manipulator_body::velocityRequest_<ContainerAllocator>& v)
  {
    s << indent << "sec_int: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sec_int);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILE_MANIPULATOR_BODY_MESSAGE_VELOCITYREQUEST_H
